apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - image: httpd
    name: podcon
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /var/www/html/
        name: myvol
  volumes:
  - name: myvol
    persistentVolumeClaim:
     claimName: mypvc1
