apiVersion: v1 # version of kind or service
kind: Pod        # name of service or component
metadata:         # detail about kind(pod)
  name: akashp1
  labels:
    app: test1
spec:   # specification of pod like container details etc
  containers:
  - name: akashcon
    image: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myweb1
spec:
  type: NodePort
  selector:
    app: test1
  ports:
    - port: 1123
      targetPort: 80
      nodePort: 30002

