apiVersion: v1  # to check version 'kubectl api-resources'
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 5
  selector:
    drink: tea
  template:
    metadata:
      labels:
          drink: tea
    spec:
      containers:
      - name: akashcon1
        image: httpd
        ports:
        - containerPort: 80
